nomeSistema=ESafra
host=localhost
schema=esafra
schema_log=esafra_log

schema_licenceObserver=aplicativosjav09
host_licenceObserver=mysql.aplicativosjava.kinghost.net

#nome_classe_funcionarioServiceImpl_local=br.com.srcsoftware.sistema.pessoa.funcionario.FuncionarioServiceImpl

# Regra de Utilização dos Modulos da Framework
# Legenda: 
## pessoa (PessoaPO,DocumentoPO,EnderecoPO,PessoaFisicaPO,PessoaJuridicaPO)
## cliente (ClientePO)
## fornecedor (FornecedorPO)
## funcionario (FuncionarioPO)
## financeiro (FinanceiroPO,ContaPagarPO,ContaReceberPO,TipoFormaPagamentoPO,FormaPagamentoPO,TituloPO,TituloPagarPO,TituloReceberPO,DespesaPO,ReceitaPO,ControleCaixaPO)				
acesso_framework=pessoa cliente funcionario

tolerancia_recebimento_sem_juros=5

#*** acessonegado.jsp ***
text.tela.acesso_negado = O endereço informado não existe!<br />

# KEY GERAL #
mensagem = {0}

# KEY SUCESSO #
sucesso = Operação realizada com sucesso.
sucesso2 = Operação realizada com sucesso.<br />{0}
falha = Operação não realizada.<br />Causa:{0}

text.erro404=Página solicitada não encontrada!
text.erro500=A operação solicitada gerou um ERRO inesperado no servidor!